### PR TITLE
Upgrade to zonkyio/embedded-postgres v2.0.1

### PR DESCRIPTION
**Pull request by rafaeldelboni**
**Breaking changes:**
Upgrade to PostgreSQL 14.5 (https://github.com/zonkyio/embedded-postgres/issues/93)

**Other changes:**
https://github.com/zonkyio/embedded-postgres/releases/tag/v2.0.0
https://github.com/zonkyio/embedded-postgres/releases/tag/v2.0.1

### CODE REVIEW

**Comment by Bigsy** [comment]
Cheers, I'll push a new clojars version tomorrow and let you know

**Comment by Bigsy** [comment]
Apologise for delay, will do this this evening when I get homw

**Comment by Bigsy** [comment]
Uploaded to clojars, sorry for delay

**Comment by rafaeldelboni** [comment]
No problems! 🎉

**Pull request merged**
